# frontend/Dockerfile.dev
FROM node:18-alpine

# Install build dependencies and sqlite
RUN apk add --no-cache \
    python3 \
    python3-dev \
    py3-pip \
    py3-setuptools \
    make \
    g++ \
    sqlite \
    sqlite-dev \
    libc6-compat

# Set working directory
WORKDIR /app/frontend

# Copy package files
COPY package*.json ./

# Install dependencies with rebuild of sqlite3
RUN npm install --verbose
RUN npm rebuild sqlite3 --build-from-source

# Install next globally to ensure the CLI is available
RUN npm install -g next

# Copy the rest of the application files
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]