name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Define project directory and repo URL
            PROJECT_DIR="/home/diego/code"
            REPO_URL="git@github.com:$GITHUB_REPOSITORY.git"

            # Check if project directory exists and is not empty
            if [ ! -d "$PROJECT_DIR" ] || [ -z "$(ls -A $PROJECT_DIR)" ]; then
              git clone "$REPO_URL" "$PROJECT_DIR"
            fi

            # Navigate to project directory
            cd "$PROJECT_DIR"

            # Pull latest changes (if already cloned)
            git pull origin master

            # Install dependencies
            npm install

            # Build the project
            npm run build

            # Clean up node_modules to save space
            rm -rf node_modules

            # Stop previous PM2 process (if it exists)
            pm2 stop my-app || true

            # Start the app with PM2
            pm2 start npm --name "my-app" -- start -p port
