name: Deploy to VPS
on:
  push:
    branches:
      - main
env:
  PROJECT_DIR: "/home/diego/code/"
  REPO_URL: "https://github.com/${{ github.repository }}.git"
  HOST: ${{ secrets.VPS_HOST }}
  USERNAME: ${{ secrets.VPS_USERNAME }}
  SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: $HOST
          username: $USERNAME
          key: $SSH_KEY
          script: |
            # Define project directory and repo URL
            echo "PROJECT_DIR: $PROJECT_DIR"
            echo "REPO_URL: $REPO_URL"

            # Navigate to project directory
            cd "$PROJECT_DIR"

            # Check if project directory exists and is not empty
            if [ ! -d "$PROJECT_DIR" ] || [ -z "$(ls -A $PROJECT_DIR)" ]; then
              echo "Cloning repository"
              git clone "$REPO_URL" 
            fi

            # Pull latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Build the project
            npm run build

            # Clean up node_modules to save space
            rm -rf node_modules

            # Stop previous PM2 process (if it exists)
            pm2 stop my-app || true

            # Start the app with PM2
            pm2 start npm --name "my-app" -- start
